In [47]:
import numpy as np
from scipy import linalg
import math

ModuleNotFoundError: No module named 'LatticeDrawing'

Input: Matriz Geradora do reticulado $\Lambda$

As isometrias são dadas pelas transformações lineares:

$\phi_1(x,y) = (x,y)$

$\phi_2(x,y) = (-x,-y)$

$\phi_3(x,y) = (-x,y)$ 

$\phi_4(x,y) = (x,-y)$

$\phi_5(x,y) = (y,x)$

$\phi_6(x,y) = (-y,x)$

$\phi_7(x,y) = (-y,x)$ 

$\phi_8(x,y) = (y,-x)$ 


In [ ]:
# Matriz do Reticulado
matrixLambda = np.matrix('0 6; 3 3') #- (0,2(r+1)), (r+1,r+1))
#matrixLambda = np.matrix('5 1; 2 4') #- (2r+ 1,1),(r,r+2)

# Matriz das Isometrias (\phi)'s
matrixIso1 = np.matrix('1 0; 0 1')
matrixIso2 = np.matrix('-1 0; 0 -1')
matrixIso3 = np.matrix('-1 0; 0 1')
matrixIso4 = np.matrix('1 0; 0 -1')
matrixIso5 = np.matrix('0 1; 1 0')
matrixIso6 = np.matrix('0 -1; -1 0')
matrixIso7 = np.matrix('0 -1; 1 0')
matrixIso8 = np.matrix('0 1; -1 0')

list_matrixIso = [matrixIso1, matrixIso2, matrixIso3, matrixIso4, matrixIso5, matrixIso6, matrixIso7, matrixIso8]

In [ ]:
def list_newlattices(matrixLambda, list_matrixIso):
    
    list_lattices = []
    for matrix in list_matrixIso:
        list_lattices.append(np.dot(matrixLambda, matrix))

    return list_lattices

In [48]:
for matrix in list_newlattices(matrixLambda, list_matrixIso):
    print(matrix)

[[0 6]
 [3 3]]
[[ 0 -6]
 [-3 -3]]
[[ 0  6]
 [-3  3]]
[[ 0 -6]
 [ 3 -3]]
[[6 0]
 [3 3]]
[[-6  0]
 [-3 -3]]
[[ 6  0]
 [ 3 -3]]
[[-6  0]
 [-3  3]]


In [ ]:
def ver_interger_solut(matrix1, matrix2): #Verifica se as linhas da matriz 2 podem ser escritas como combinação linear inteira das linhas da matriz 1

    for row in matrix2: 
        for list_numbers in linalg.solve(matrix1, row.transpose()).tolist():
            for number in list_numbers:
                if number//1 != number:
                    return False
    return True

def compare_lattice(matrix1, matrix2): #Verifica se os reticulados são iguais a partir da matriz geradora

    if ver_interger_solut(matrix1, matrix2) and ver_interger_solut(matrix2, matrix1): 
        return True
    return False

def show_equals(matrixLambda, list_matrixIso): #Exibe quais são os reticulados que são iguais ao inicial e quais não são

    mlattices = list_newlattices(matrixLambda, list_matrixIso)

    for index in range(len(mlattices)):
        if compare_lattice(matrixLambda.transpose(), mlattices[index]):
            print("O Reticulado gerado pela isometria (\phi)", index+1, "é igual ao original")
        else:
            print("O Reticulado gerado pela isometria (\phi)", index+1, "é diferente do original")

In [ ]:
show_equals(matrixLambda, list_matrixIso)

O Reticulado gerado pela isometria (\phi) 1 é igual ao original
O Reticulado gerado pela isometria (\phi) 2 é igual ao original
O Reticulado gerado pela isometria (\phi) 3 é igual ao original
O Reticulado gerado pela isometria (\phi) 4 é igual ao original
O Reticulado gerado pela isometria (\phi) 5 é igual ao original
O Reticulado gerado pela isometria (\phi) 6 é igual ao original
O Reticulado gerado pela isometria (\phi) 7 é igual ao original
O Reticulado gerado pela isometria (\phi) 8 é igual ao original
